### ISSUE TITLE
Immediate file types and extractors we are interested in registering

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_registry#21]
This issue can be used to vaguely track specific filetypes and extractors we want in the registry:

- [ ] CIF -> https://github.com/cod-developers/cod-tools (@ml-evs)
- [ ] NeXuS -> https://github.com/dlce-eva/python-nexus (@ml-evs)
- [ ] TIF files from SEM machines (see below) -> https://github.com/kit-data-manager/SEM-Mapping-Tool
    - This is a great example as it takes a generic format (TIF), specialises it into TIF files produced by Zeiss instruments for SEM, and extracts metadata in a way that is beyond what a "casual" parser would do (OCR on the metadata in the image, rather than just reading a file) (developed by @reetuelzajoseph -- hope you don't mind me tagging you!) -- it also has a well-defined set of schemas already!

![image](https://user-images.githubusercontent.com/7916000/220738373-107da3eb-6181-4fa0-982f-6fd84325e0f9.png)

**Comment by PeterKraus** [comment]
Maybe something to keep track of for Yard.
