### ISSUE TITLE
Make use of example files for each type in registry

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_registry#34]
- [ ] Make sure the URLs are resolvable through Fly (probably pointing to GitHub raw links)
- [ ] Add the files as examples in the file types models and expose them for validation
- [ ] Validate entries in the `data` folder and make sure they correspond to registered file types

**Comment by PeterKraus** [comment]
This would mean that a CI in the registry repo would use the api package to check whether the filetypes in the example folder can be processed using the extractors in the example folder.
