### ISSUE TITLE
Use fly volumes to run a real database

### ISSUE THREAD

**Issue by ml-evs** [marda-alliance/metadata_extractors_registry#6]
This will enable free-text search over entries (if we use e.g., Mongo). Can also just use sqlite or something if that ends up being easier.

https://fly.io/docs/reference/volumes/

**Comment by PeterKraus** [comment]
Deployment of [datatractor/yard](https://yard.datatractor.org/) now works via docker, closing.

**Comment by ml-evs** [comment]
We still don't use a real database though... not necessarily a problem yet though
